Repository GoGo-Ring/dongoorami-frontend, pull requests merged in 2024-02, with the labels that each got.

#3 Init: [#1] 프로젝트 초기 세팅
  .eslintrc.cjs
  .gitignore
  README.md
  apis/index.ts
  app/layout.tsx
  app/page.tsx
  components.json
  components/ui/button.tsx
  hooks/.empty
  libs/utils.ts
  next.config.mjs
  package.json
  pnpm-lock.yaml
  postcss.config.cjs
  styles/globals.css
  tailwind.config.js
  tsconfig.json
Labels: Init

#5 Build: [#4] lint 및 git hooks 설정
  .commitlintrc.json
  .eslintrc.cjs
  .husky/commit-msg
  .husky/pre-commit
  .prettierrc
  apis/index.ts
  app/layout.tsx
  app/page.tsx
  components/ui/button.tsx
  libs/utils.ts
  package.json
  pnpm-lock.yaml
Labels: Build

#7 Chore: [#6] Feature 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/issue--feature-request.md
Labels: chore

#9 Chore: [#8] Bug 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/issue--bug-report.md
Labels: chore

#12 Chore: 커밋 차단 범위 지정
  .husky/pre-commit
Labels: chore

#13 Feat: [#10] shadcn/ui 모듈 추가
  .eslintrc.cjs
  app/layout.tsx
  app/page.tsx
  components.json
  components/accordion.tsx
  components/alert-dialog.tsx
  components/avatar.tsx
  components/badge.tsx
  components/button.tsx
  components/checkbox.tsx
  components/dialog.tsx
  components/input.tsx
  components/label.tsx
  components/progress.tsx
  components/select.tsx
  components/sheet.tsx
  components/tabs.tsx
  components/toast.tsx
  package.json
  pnpm-lock.yaml
  styles/globals.css
  tailwind.config.js
Labels: feature

#23 Feat: [#14] 소셜로그인 UI 및 인가코드 받아오기
  app/layout.tsx
  app/login/_components/oauth-button/o-auth-button.tsx
  app/login/_components/oauth-button/utils.ts
  app/login/page.tsx
  public/kakao-icon.svg
  public/naver-icon.svg
  styles/globals.css
  tailwind.config.js
Labels: feature, style

#22 Feat: [#15] 구인 입력 페이지 구성하기 (데스크탑)
  app/recruitment/new/_components/double-thumb-slider.tsx
  app/recruitment/new/constants.ts
  app/recruitment/new/page.tsx
  components/radio-group.tsx
  components/slider.tsx
  components/textarea.tsx
  package.json
  pnpm-lock.yaml
Labels: feature, style

#31 Chore: [#30] Issue template, PR template 내용 수정
  .github/ISSUE_TEMPLATE/issue--feature-request.md
  .github/pull_request_template.md
Labels: chore

#20 Feat: [#17] 검색 및 결과 페이지의 공연 카드 컴포넌트 UI 구현
  app/search/_component/PerformanceInfoCard.tsx
  utils/dateFormatter.ts
Labels: feature, style

#32 Feat: [#25] 폼 상태 관리 및 유효성 검사를 위한 useForm 구현
  hooks/useForm.ts
Labels: feature

#38 Chore: [#36] tanstack-query provider 추가
  app/providers.tsx
Labels: chore

#33 Feat: [#29] 메인 페이지와 검색 및 결과 페이지에서 사용되는 동행 구함 카드 컴포넌트 UI 구현
  app/_components/CompanionRecruitmentCard.tsx
Labels: feature, style

#28 Feat: [#27] 동행 구인 필터 UI 구현
  app/_components/CompanionRecruitmentFilter.tsx
  app/_components/Filter.tsx
  app/_components/constants.ts
Labels: feature, style

#49 Fix: [#46] export 키워드 제거
  app/layout.tsx
Labels: bug

#45 Feat: [#40] 헤더 컴포넌트 생성
  app/layout.tsx
  components/header/constants.ts
  components/header/index.tsx
  components/header/main-nav.tsx
  components/header/mobile-link.tsx
  components/header/mobile-nav.tsx
  styles/globals.css
  tailwind.config.js
Labels: feature

#42 Refactor: [#41] 동행 구함 카드 컴포넌트 내부에 props 전달
  app/_components/CompanionRecruitmentCard.tsx
  utils/dateFormatter.ts
Labels: refactor

#44 Feat [#39]: form 유효성 검사 기능 추가 및 적용
  app/recruitment/new/_components/common/form.tsx
  app/recruitment/new/_components/error.tsx
  app/recruitment/new/_components/form-filed/field.tsx
  app/recruitment/new/_components/form-filed/index.tsx
  app/recruitment/new/_components/form.tsx
  app/recruitment/new/constants.ts
  app/recruitment/new/page.tsx
  hooks/useForm.ts
  hooks/useForm/index.ts
  hooks/useForm/types.ts
Labels: feature

#47 Feat: [#46] icon 컴포넌트 추가
  components/icon/icons/alarm.tsx
  components/icon/icons/chat.tsx
  components/icon/icons/chevron-down.tsx
  components/icon/icons/eye.tsx
  components/icon/icons/filter.tsx
  components/icon/icons/heart.tsx
  components/icon/icons/index.ts
  components/icon/icons/menu.tsx
  components/icon/icons/message.tsx
  components/icon/icons/search.tsx
  components/icon/icons/star.tsx
  components/icon/icons/user.tsx
  components/icon/index.tsx
  components/icon/utils.ts
Labels: feature

#52 Feat: [#50] 검색 기능 추가
  app/layout.tsx
  components/header/index.tsx
  components/header/search-bar.tsx
  tailwind.config.js
Labels: feature

#53 Style: [#51] 동행 입력 페이지 반응형 css 추가
  app/recruitment/new/_components/form-field/field.tsx
  app/recruitment/new/_components/form-field/index.tsx
  app/recruitment/new/page.tsx
Labels: style, refactor
