Repository GoGo-Ring/dongoorami-frontend, pull requests merged in 2024-03, with the labels that each got.

#63 Feat : [#60] filter 컴포넌트 수정
  app/_components/CompanionRecruitmentFilter.tsx
  app/_components/companion-recruitment-filter.tsx
  app/_components/filter-tabs.tsx
  app/_components/performance-filter.tsx
  app/_components/single-filter.tsx
  app/layout.tsx
  app/recruitment/new/_components/form-field/field.tsx
  app/recruitment/new/_components/form-field/index.tsx
  app/recruitment/new/page.tsx
  components/header/index.tsx
  components/header/search-bar.tsx
  components/icon/icons/alarm.tsx
  components/icon/icons/chat.tsx
  components/icon/icons/chevron-down.tsx
  components/icon/icons/eye.tsx
  components/icon/icons/filter.tsx
  components/icon/icons/heart.tsx
  components/icon/icons/index.ts
  components/icon/icons/menu.tsx
  components/icon/icons/message.tsx
  components/icon/icons/search.tsx
  components/icon/icons/star.tsx
  components/icon/icons/user.tsx
  components/icon/index.tsx
  components/icon/utils.ts
  constants/filterField.ts
  tailwind.config.js
  utils/joinQuery.ts
Labels: feature

#74 Refactor: [#73] 동행 구함 카드 컴포넌트에 icon 추가
  app/_components/CompanionRecruitmentCard.tsx
Labels: refactor

#59 Feat: [#56] 이미지 입력, 달력 입력 추가
  app/recruitment/new/_components/form-field/calendar-field.tsx
  app/recruitment/new/_components/form-field/field.tsx
  app/recruitment/new/_components/form-field/index.tsx
  app/recruitment/new/constants.ts
  app/recruitment/new/page.tsx
  components/calendar.tsx
  hooks/useForm/index.ts
  hooks/useForm/types.ts
Labels: feature

#65 Feat: [#64] 동행 입력 페이지 post 요청 추가
  app/recruitment/new/_components/fields/calendar-field.tsx
  app/recruitment/new/_components/fields/field.tsx
  app/recruitment/new/_components/fields/image-field.tsx
  app/recruitment/new/_components/fields/index.tsx
  app/recruitment/new/_components/fields/input-field.tsx
  app/recruitment/new/_components/fields/radio-field.tsx
  app/recruitment/new/_components/fields/select-field.tsx
  app/recruitment/new/_components/fields/slider-field.tsx
  app/recruitment/new/_components/fields/textarea-field.tsx
  app/recruitment/new/_components/form-field/index.tsx
  app/recruitment/new/_components/form.tsx
  app/recruitment/new/constants.ts
  app/recruitment/new/page.tsx
  hooks/useForm/index.ts
  utils/apiRequestAdapter.ts
Labels: feature, refactor

#55 Refactor [#43] 동행 구함 Filter 컴포넌트 내부에 props 전달
  app/_components/CompanionRecruitmentFilter.tsx
  app/_components/Filter.tsx
  app/_components/companion-recruitment-filter.tsx
  app/_components/constants.ts
  app/_components/filter-field/checkbox-select.tsx
  app/_components/filter-field/input-field.tsx
  app/_components/filter-field/radio-field.tsx
  app/_components/filter-field/select-field.tsx
  constants/filterField.ts
Labels: refactor

#62 Feat: [#61] user page 생성
  apis/index.ts
  apis/member.ts
  app/layout.tsx
  app/users/[id]/_components/complete-button.tsx
  app/users/[id]/_components/editable-image.tsx
  app/users/[id]/_components/editable-input.tsx
  app/users/[id]/_components/info.tsx
  app/users/[id]/_components/review.tsx
  app/users/[id]/constants.ts
  app/users/[id]/page.tsx
  components/header/index.tsx
  components/image-uploader.tsx
  hooks/mutations/useMutationMember.ts
  hooks/mutations/useMutationProfileImage.ts
  hooks/queries/useFetchMember.ts
  mocks/handlers/members.ts
  next.config.mjs
  utils/dateFormatter.ts
Labels: feature

#58 Feat: [#57] 공연 필터 컴포넌트에 ref 추가
  app/_components/companion-recruitment-filter.tsx
  app/_components/filter-field/button-select.tsx
  app/_components/filter-field/input-field.tsx
  app/_components/filter-field/select-field.tsx
  app/_components/filter-tabs.tsx
  app/_components/performance-filter.tsx
  app/_components/single-filter.tsx
  app/recruitment/new/_components/form-field/field.tsx
  app/recruitment/new/_components/form-field/index.tsx
  utils/joinQuery.ts
Labels: feature

#89 Feat: [#83] message 기능 관련 네트워크 통신 로직 추가
  apis/index.ts
  apis/message.ts
  apis/scheme/message.ts
  app/recruitment/new/_components/form-field/field.tsx
  app/recruitment/new/_components/form-field/index.tsx
  hooks/mutations/useMutationMessage.ts
  hooks/queries/useFetchMessage.ts
  mocks/handlers/index.ts
  mocks/handlers/message.ts
Labels: feature

#67 Feat: [#66] 검색 페이지 추가
  app/_components/filter-field/button-select.tsx
  app/_components/filter-field/checkbox-select.tsx
  app/search/page.tsx
Labels: feature

#92 Fix: [#91] Button-select 컴포넌트 오류 수정
  app/_components/filter-field/button-select.tsx
  app/_components/filter-field/checkbox-select.tsx
Labels: fix

#86 Feat: [#78] 후기 페이지 후기 작성 컴포넌트 생성
  app/review/_components/review-form.tsx
  app/review/_components/star-rating.tsx
  components/collapsible.tsx
  package.json
  pnpm-lock.yaml
Labels: feature

#70 Feat: [#69] 댓글 입력 컴포넌트 추가
  apis/accompany.ts
  apis/scheme/comment.ts
  app/recruitment/[id]/_components/comment/form.tsx
  app/recruitment/[id]/_components/comment/index.ts
  app/recruitment/[id]/_components/comment/list.tsx
  app/recruitment/[id]/_components/comment/section.tsx
  app/recruitment/[id]/page.tsx
  hooks/mutations/useMutationComment.ts
  hooks/queries/useFetchComments.ts
  mocks/handlers/comment.ts
  mocks/handlers/index.ts
Labels: feature, style

#75 Feat: [#71] 구인 상세페이지 컴포넌트 구현 (댓글, 동행하기 제외)
  apis/accompany.ts
  apis/scheme/accompany.ts
  app/recruitment/[id]/_components/field.tsx
  app/recruitment/[id]/_components/post-status.tsx
  app/recruitment/[id]/_components/profile.tsx
  app/recruitment/[id]/_components/section.tsx
  app/recruitment/[id]/_components/skeletons/page.tsx
  app/recruitment/[id]/error.tsx
  app/recruitment/[id]/loading.tsx
  app/recruitment/[id]/page.tsx
  hooks/queries/useQueryCompanionPost.ts
  mocks/handlers/accompany.ts
  mocks/handlers/index.ts
Labels: feature, style

#106 Fix: [#105] 동행 구함 필터의 options 객체, 체크박스의 fieldName 수정
  app/_components/companion-recruitment-filter.tsx
Labels: fix

#79 Feat: [#77] 구인 입력 페이지 에러와 로딩 처리
  app/recruitment/new/_components/page-skeleton.tsx
  app/recruitment/new/error.tsx
  app/recruitment/new/loading.tsx
  app/recruitment/new/page.tsx
Labels: feature, style

#88 Feat: [#82] 구인 입력 페이지 수정 데이터 받아오기
  apis/scheme/accompany.ts
  app/recruitment/new/_components/fields/image-field.tsx
  app/recruitment/new/_components/fields/input-field.tsx
  app/recruitment/new/page.tsx
  app/recruitment/new/utils.ts
  hooks/queries/useFetchCompanionPost.ts
  mocks/handlers/accompany.ts
  utils/apiRequestAdapter.ts
Labels: feature, refactor

#102 Refactor: [#101] useForm 리팩토링
  app/recruitment/[id]/_components/comment/form.tsx
  app/recruitment/new/_components/fields/calendar-field.tsx
  app/recruitment/new/_components/fields/slider-field.tsx
  app/recruitment/new/_components/form.tsx
  app/recruitment/new/constants.ts
  hooks/useForm/index.ts
  hooks/useForm/types.ts
Labels: refactor

#117 Fix: [#116] 누락된 birthDate 스키마 수정
  app/users/[id]/page.tsx
  mocks/handlers/accompany.ts
Labels: fix

#108 Feat: [#100] 공연 정보 페이지 관람 후기 컴포넌트 추가
  app/performance/_components/review/form.tsx
  app/recruitment/[id]/_components/comment/form.tsx
  app/review/_components/star-rating.tsx
  components/error-text.tsx
  hooks/useForm/index.ts
  hooks/useForm/types.ts
Labels: feature

#111 Feat: [#110] 공연 상세페이지 ui 추가
  apis/scheme/accompany.ts
  app/recruitment/[id]/_components/apply.tsx
  app/recruitment/[id]/_components/post-status.tsx
  app/recruitment/[id]/page.tsx
  mocks/handlers/accompany.ts
Labels: feature, style

#120 Refactor: [#118] 회원가입 및 유저 정보 관련 기능 수정
  apis/index.ts
  apis/member.ts
  apis/scheme/member.ts
  app/register/page.tsx
  app/users/[id]/_components/editable-image.tsx
  app/users/[id]/page.tsx
  hooks/mutations/useMutationProfileImage.ts
  hooks/mutations/useMutationRegisterMember.ts
  hooks/mutations/useMutationUpdateMember.ts
  mocks/handlers/accompany.ts
  mocks/handlers/members.ts
  next.config.mjs
Labels: refactor

#72 Feat: [#68] 검색 페이지 get 요청 추가
  apis/companion.ts
  apis/performance.ts
  apis/scheme/accompany.ts
  apis/scheme/performance.ts
  app/_components/filter-field/select-field.tsx
  app/search/_component/performance-info-card.tsx
  app/search/page.tsx
  hooks/queries/useFetchCompanions.ts
  hooks/queries/useFetchPerformances.ts
  mocks/handlers/accompany.ts
  mocks/handlers/companion.ts
  mocks/handlers/index.ts
  mocks/handlers/performances.ts
Labels: feature

#93 Feat: [#90] message page UI 구현
  app/message/_components/main-list.tsx
  app/message/_components/mobile-list.tsx
  app/message/_utils/pagination.ts
  app/message/constatns.ts
  app/message/page.tsx
  components/pagination.tsx
Labels: feature

#103 Feat: [#99] 공연 정보 페이지 UI 추가
  app/performance/_components/info-item-with-button.tsx
  app/performance/_components/info-item.tsx
  app/performance/_components/toggle.tsx
  app/performance/page.tsx
Labels: feature

#115 Feat: [#113] 댓글에 수정 및 삭제 기능 추가
  apis/accompany.ts
  apis/scheme/comment.ts
  app/recruitment/[id]/_components/comment/form.tsx
  app/recruitment/[id]/_components/comment/list.tsx
  app/recruitment/[id]/_components/comment/list/buttons.tsx
  app/recruitment/[id]/_components/comment/list/content.tsx
  app/recruitment/[id]/_components/comment/list/index.tsx
  app/recruitment/[id]/_components/comment/section.tsx
  app/recruitment/[id]/_components/profile.tsx
  hooks/mutations/useMutationComment.ts
  hooks/mutations/useMutationDeleteComment.ts
  hooks/mutations/useMutationUpdateComment.ts
  mocks/handlers/comment.ts
Labels: feature

#127 Refactor: [#126] 헤더 아이콘 네비게이팅 주소 추가
  components/header/index.tsx
Labels: refactor

#124 Feat: [#121] 쪽지 확인 페이지 member api 로직 추가
  apis/accompany.ts
  apis/scheme/accompany.ts
  app/message/write/_components/form.tsx
  app/message/write/_components/list.tsx
  app/message/write/page.tsx
  app/recruitment/[id]/page.tsx
  hooks/queries/useFetchMemberById.ts
  hooks/queries/useFetchMessageById.ts
  mocks/handlers/accompany.ts
  mocks/handlers/members.ts
  mocks/handlers/message.ts
Labels: feature

#131 Feat: [#119] 동행 입력,수정 페이지 api 연동
  apis/accompany.ts
  apis/scheme/accompanyDetail.ts
  app/recruitment/[id]/_components/field.tsx
  app/recruitment/[id]/_components/post-status.tsx
  app/recruitment/[id]/page.tsx
  app/recruitment/new/page.tsx
  hooks/mutations/useMutationCreateCompanyPost.ts
  hooks/mutations/useMutationDeleteCompanyPost.ts
  hooks/mutations/useMutationUpdateCompanyPost.ts
  hooks/queries/useFetchCompanionPost.ts
  hooks/queries/useQueryCompanionPost.ts
  mocks/handlers/accompany.ts
  mocks/handlers/accompanyDetail.ts
  mocks/handlers/index.ts
  next.config.mjs
Labels: feature, refactor

#147 Fix: [#146] 타입 수정된 부분 재 반영
  utils/starRating.ts
Labels: fix

#145 Chore: [#144] 허스키에 commit 시 tsc 검사 추가
  .gitignore
  .husky/pre-commit
  package.json
Labels: chore

#130 Feat: [#76] 홈 화면 스타일 구현
  app/_components/CompanionRecruitmentCard.tsx
  app/_components/DummyCard.tsx
  app/_components/MainFilter.tsx
  app/_components/MobileFilter.tsx
  app/_components/StyledCarousel.tsx
  app/page.tsx
  components/carousel.tsx
  package.json
  pnpm-lock.yaml
  tailwind.config.js
Labels: feature, style

#123 Feat: [#122] 내 정보, 다른 유저 정보 페이지 분리
  apis/member.ts
  apis/scheme/member.ts
  app/layout.tsx
  app/users/[id]/page.tsx
  app/users/_components/complete-button.tsx
  app/users/_components/editable-image.tsx
  app/users/_components/editable-input.tsx
  app/users/_components/info.tsx
  app/users/_components/review.tsx
  app/users/constants.ts
  app/users/page.tsx
  components/header/index.tsx
  components/header/mobile-nav.tsx
  components/image-uploader.tsx
  hooks/queries/useFetchProfile.ts
  mocks/handlers/members.ts
Labels: feature

#133 Refactor: [#132] useForm 리팩토링 및 적용
  app/recruitment/new/_components/fields/calendar-field.tsx
  app/recruitment/new/_components/fields/image-field.tsx
  app/recruitment/new/_components/fields/input-field.tsx
  app/recruitment/new/_components/fields/radio-field.tsx
  app/recruitment/new/_components/fields/select-field.tsx
  app/recruitment/new/_components/fields/slider-field.tsx
  app/recruitment/new/_components/fields/textarea-field.tsx
  app/recruitment/new/_components/form.tsx
  app/recruitment/new/constants.ts
  app/recruitment/new/page.tsx
  app/recruitment/new/utils.ts
  hooks/useForm/index.ts
  hooks/useForm/types.ts
Labels: refactor

#140 Feat: [#129] 검색 페이지 동행 구인글 및 공연글 필터링 목록 조회 api 연결
  apis/companion.ts
  apis/performance.ts
  apis/scheme/accompany.ts
  apis/scheme/performance.ts
  app/_components/CompanionRecruitmentCard.tsx
  app/_components/DummyCard.tsx
  app/_components/companion-recruitment-filter.tsx
  app/_components/performance-filter.tsx
  app/performance/[id]/page.tsx
  app/search/_component/companion-recruitment-list.tsx
  app/search/_component/filter-search.tsx
  app/search/_component/performance-info-card.tsx
  app/search/_component/performance-info-list.tsx
  app/search/_component/useIntersectionObserver.ts
  app/search/page.tsx
  constants/filterField.ts
  hooks/infinite/useInfiniteAccompanies.ts
  hooks/infinite/useInfinitePerformances.ts
  hooks/queries/useFetchCompanions.ts
  hooks/queries/useFetchPerformances.ts
  mocks/handlers/accompany.ts
  mocks/handlers/companion.ts
  mocks/handlers/index.ts
  mocks/handlers/performances.ts
  next.config.mjs
  utils/joinQuery.ts
Labels: feature

#162 Fix: [#161] package module type 제거
  package.json
Labels: fix

#137 Feat: [#134] 동행 입력 페이지 이미지다중 입력, checkbox 입력
  app/recruitment/new/_components/error.tsx
  app/recruitment/new/_components/fields/calendar-field.tsx
  app/recruitment/new/_components/fields/checkbox-field.tsx
  app/recruitment/new/_components/fields/image-field.tsx
  app/recruitment/new/_components/fields/index.tsx
  app/recruitment/new/_components/fields/input-field.tsx
  app/recruitment/new/_components/fields/radio-field.tsx
  app/recruitment/new/_components/fields/select-field.tsx
  app/recruitment/new/_components/fields/slider-field.tsx
  app/recruitment/new/_components/fields/textarea-field.tsx
  app/recruitment/new/constants.ts
  app/recruitment/new/page.tsx
  app/recruitment/new/utils.ts
  components/icon/icons/index.ts
  components/icon/icons/remove.tsx
Labels: feature, refactor

#139 Feat: [#138] 동행 입력 페이지에 search 컴포넌트 추가
  app/recruitment/new/_components/fields/index.tsx
  app/recruitment/new/_components/fields/search-button-field.tsx
  app/recruitment/new/constants.ts
  app/recruitment/new/page.tsx
  components/command.tsx
  components/popover.tsx
  package.json
  pnpm-lock.yaml
Labels: feature

#136 Feat: [#135] 토큰 여부에 따른 리다이렉트
  app/auth.tsx
  app/layout.tsx
Labels: feature

#158 Feat: [#157] 동행 구함 필터의 동행 목적에 대한 항목을 추가합니다
  app/_components/companion-recruitment-filter.tsx
  app/_components/filter-field/checkbox-select.tsx
  constants/filterField.ts
Labels: feature

#156 Feat: [#155] 리뷰페이지 체크박스 UI 추가
  app/review/_components/constants.ts
  app/review/_components/review-form.tsx
  app/review/page.tsx
Labels: feature

#160 Style: [#159] 검색 페이지 UI 수정
  app/_components/filter-tabs.tsx
  app/search/_component/filter-search.tsx
  app/search/_component/performance-info-list.tsx
Labels: style

#150 Feat: [#149] 동행 입력 페이지에 공연 목록 search 입력을 위한 msw와 api 추가
  apis/accompany.ts
  apis/scheme/accompanyInput.ts
  app/recruitment/new/_components/fields/search-button-field.tsx
  hooks/queries/useFetchCompanionPerformances.ts
  mocks/handlers/accompanyPerformances.ts
  mocks/handlers/index.ts
Labels: feature

#143 Feat: [#125] 구인 상세 페이지의 동행하기 버튼 댓글 msw api 추가
  apis/accompany.ts
  app/recruitment/[id]/_components/comment/form.tsx
  app/recruitment/[id]/_components/comment/list/index.tsx
  app/recruitment/[id]/_components/comment/section.tsx
  hooks/mutations/useMutationComment.ts
  hooks/mutations/useMutationConfirmCompanion.ts
  hooks/mutations/useMutationCreateCompanyComment.ts
  hooks/mutations/useMutationDeleteComment.ts
  hooks/mutations/useMutationUpdateComment.ts
  hooks/useForm/index.ts
  mocks/handlers/accompanyDetail.ts
  mocks/handlers/comment.ts
Labels: feature

#148 Feat: [#142] 동행 상세 페이지의 동행하기 버튼 관련 ui 추가 및 msw 연결
  apis/accompany.ts
  apis/scheme/comment.ts
  app/recruitment/[id]/_components/apply.tsx
  app/recruitment/[id]/_components/apply/form.tsx
  app/recruitment/[id]/_components/apply/index.ts
  app/recruitment/[id]/_components/apply/list.tsx
  app/recruitment/[id]/_components/apply/section.tsx
  app/recruitment/[id]/_components/comment/form.tsx
  app/recruitment/[id]/_components/comment/list/content.tsx
  app/recruitment/[id]/_components/comment/list/index.tsx
  app/recruitment/[id]/_components/comment/section.tsx
  app/recruitment/[id]/_components/post-status.tsx
  app/recruitment/[id]/_components/section.tsx
  app/recruitment/[id]/page.tsx
  hooks/queries/useFetchComments.ts
  mocks/handlers/comment.ts
Labels: feature, style

#168 Feat: [#151] 메인페이지 기능 추가 및 스타일
  apis/performance.ts
  app/_components/MainFilter.tsx
  app/_components/MobileFilter.tsx
  app/_components/StyledCarousel.tsx
  app/page.tsx
  app/search/_component/companion-recruitment-list.tsx
  hooks/infinite/useInfiniteAccompanies.ts
  hooks/queries/useFetchCarouselPerformances.ts
  mocks/handlers/index.ts
  tailwind.config.js
Labels: feature, style

#178 Feat: [#177] 동행 상세페이지 api 연결 완료
  apis/accompany.ts
  app/recruitment/[id]/_components/apply/form.tsx
  app/recruitment/[id]/_components/apply/index.ts
  app/recruitment/[id]/_components/apply/list.tsx
  app/recruitment/[id]/_components/apply/section.tsx
  app/recruitment/[id]/_components/post-status.tsx
  app/recruitment/[id]/page.tsx
  hooks/mutations/useMutationCloseCompanyStatus.ts
Labels: feature, refactor

#167 Feat: [#166] 찜 목록 확인 기능 추가
  apis/scheme/wish.ts
  apis/wish.ts
  app/search/_component/companion-recruitment-list.tsx
  app/search/_component/performance-info-list.tsx
  app/users/[id]/page.tsx
  app/users/_components/list-item.tsx
  app/users/_components/wishes.tsx
  app/users/page.tsx
  components/scroll-area.tsx
  hooks/infinite/useInfiniteWishes.ts
  hooks/useIntersectionObserver.ts
  mocks/handlers/index.ts
  mocks/handlers/wish.ts
  package.json
  pnpm-lock.yaml
Labels: feature

#169 Feat: [#163] 공연 후기 작성 UI 추가, API 호출 함수 추가
  apis/performance.ts
  apis/scheme/performance.ts
  app/performance/[id]/page.tsx
  app/performance/_components/performance-review.tsx
  app/performance/_components/review/form.tsx
  app/search/_component/filter-search.tsx
  hooks/mutations/useMutationDeletePerformanceReview.ts
  hooks/mutations/useMutationPerformanceReviewComment.ts
  hooks/mutations/useMutationUpdatePerformanceReview.ts
  mocks/handlers/index.ts
  mocks/handlers/review.ts
Labels: feature

#181 Feat: [#170] 동행 리뷰 작성 API 추가
  apis/review.ts
  apis/scheme/accompanyReview.ts
  apis/scheme/review.ts
  app/review/[id]/page.tsx
  app/review/_components/review-form.tsx
  app/review/page.tsx
  hooks/mutations/useMutationCreateAccompanyReviews.ts
  hooks/queries/useFetchAccompanyReviewees.ts
  mocks/handlers/accompanyReview.ts
Labels: feature

#176 Style: [#173] 검색 페이지 ui 수정
  app/_components/filter-tabs.tsx
  app/search/_component/companion-recruitment-list.tsx
  app/search/_component/filter-search.tsx
Labels: style

#165 Feat: [#164] 동행 입력페이지 에 api 연결 합니다
  apis/accompany.ts
  apis/index.ts
  apis/scheme/accompanyDetail.ts
  app/recruitment/[id]/_components/apply/list.tsx
  app/recruitment/[id]/_components/comment/form.tsx
  app/recruitment/[id]/_components/comment/section.tsx
  app/recruitment/[id]/_components/profile.tsx
  app/recruitment/[id]/page.tsx
  app/recruitment/new/_components/fields/field.tsx
  app/recruitment/new/_components/fields/search-button-field.tsx
  app/recruitment/new/_components/form.tsx
  app/recruitment/new/constants.ts
  app/recruitment/new/page.tsx
  app/recruitment/new/utils.ts
  hooks/mutations/useMutationCreateCompanyPost.ts
  hooks/mutations/useMutationDeleteCompanyPost.ts
  hooks/mutations/useMutationUpdateCompanyPost.ts
  hooks/useForm/index.ts
  mocks/handlers/accompanyDetail.ts
  next.config.mjs
Labels: feature, refactor

#175 Feat: [#174] 쪽지 전송 페이지 api 연결
  apis/message.ts
  apis/scheme/accompany.ts
  apis/scheme/message.ts
  app/message/_components/main-list.tsx
  app/message/_components/mobile-list.tsx
  app/message/write/_components/form.tsx
  app/message/write/_components/list.tsx
  app/message/write/page.tsx
  hooks/.empty
  hooks/infinite/useInfiniteMessagesById.ts
  hooks/mutations/useMutationCreateMessage.ts
  hooks/queries/useFetchMessageById.ts
  mocks/handlers/accompany.ts
  mocks/handlers/message.ts
Labels: feature, refactor

#188 Chore [#186] 슬라이드 sheet 라우팅 경로 수정, mocks handler 추가
  components/header/mobile-nav.tsx
  mocks/handlers/index.ts
Labels: chore

#191 Style [#190] 동행 리뷰 컴포넌트 width 수정
  app/review/[id]/page.tsx
  app/review/_components/review-form.tsx
  mocks/handlers/accompanyReview.ts
Labels: style

#195 Fix: [#194] 인증되지 않은 유저 리다이렉트
  app/auth.tsx
Labels: fix

#185 Feat: [#184] 비로그인시 /user에서 /login이동처리 메인에서 동행구함 페이지 연결 추가
  app/_components/DummyCard.tsx
  app/_components/MainFilter.tsx
  app/_components/MobileFilter.tsx
  app/_components/companion-recruitment-card.tsx
Labels: bug, feature, fix

#193 Refactor: [#187] 동행 페이지 ui 관련 수정
  app/recruitment/new/page.tsx
Labels: style, refactor

#202 Feat: [#199] 리뷰 및 작성글 컴포넌트 추가
  apis/member.ts
  apis/review.ts
  apis/scheme/member.ts
  apis/scheme/review.ts
  app/users/_components/recieved-review.tsx
  app/users/_components/sent-review.tsx
  app/users/_components/written-comments.tsx
  app/users/_components/written-posts.tsx
  app/users/constants.ts
  app/users/page.tsx
  hooks/queries/useFetchReviews.ts
  hooks/queries/useFetchSentReview.ts
  hooks/queries/useFetchUnsentReviews.ts
  hooks/queries/useFetchWrittenComments.ts
  hooks/queries/useFetchWrittenPosts.ts
Labels: feature

#203 Refactor: [#197] 동행 구함 필터 수정
  app/_components/companion-recruitment-filter.tsx
  app/_components/filter-field/input-field.tsx
  constants/filterField.ts
Labels: refactor

#205 Fix: [#204] cors error
  apis/accompany.ts
Labels: bug

#208 Fix: [#206] 메시지 전송 페이지 연결
  app/message/_components/mobile-list.tsx
  app/users/[id]/page.tsx
Labels: fix

#210 Feat: [#209] 받은 후기 목록 컴포넌트 추가
  app/users/[id]/page.tsx
  app/users/_components/recieved-review.tsx
Labels: feature

#211 Feat: [#207] 동행 신청 시 보여지는 ui 로직 변경
  app/recruitment/[id]/_components/apply/list.tsx
  app/recruitment/[id]/page.tsx
  hooks/mutations/useMutationCreateCompanyComment.ts
Labels: feature, refactor

#213 Style: [#212] 교통 수단 -> 동행 목적
  app/recruitment/[id]/page.tsx
Labels: style
